//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aspirante_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aspirante
    {
        public long aspirante_id { get; set; }
        public string aspirante_cedula { get; set; }
        public string aspirante_nombres { get; set; }
        public string aspirante_apellidos { get; set; }
        public string aspirante_direccion { get; set; }
        public string aspirante_email { get; set; }
        public string aspirante_movil { get; set; }
        public string aspirante_genero { get; set; }
        public string aspirante_carrera_interes { get; set; }
        public string aspirante_observaciones { get; set; }
        public System.DateTime aspirante_fecha_registro { get; set; }
        public string aspirante_user_id { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Carrera Carrera { get; set; }
        public virtual Genero Genero { get; set; }
    }
}
